---
- name: set Debian audit grub cmdline
  become: 'yes'
  lineinfile:
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX {{ grub_audit_cmdline }} {{ grub_audit_backlog_cmdline }}"'
    dest: /etc/default/grub.d/99-hardening-audit.cfg
    state: present
    create: 'yes'
    mode: 0755
    owner: root
    group: root
  notify:
    - update grub
  when: ansible_os_family == "Debian"
  tags:
    - auditd
    - grub

- name: set RedHat audit grub cmdline
  become: 'yes'
  lineinfile:
    line: 'GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX {{ grub_audit_cmdline }} {{ grub_audit_backlog_cmdline }}"'
    dest: /etc/default/grub
    insertafter: '^GRUB_CMDLINE_LINUX="[a-z]+'
    state: present
    create: 'no'
    mode: 0644
    owner: root
    group: root
  notify:
    - update grub2
  when: ansible_os_family == "RedHat"
  tags:
    - auditd
    - grub

- name: check RedHat auditd ExecStartPost
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  command: grep -qo "^ExecStartPost=-/sbin/auditctl -R" /usr/lib/systemd/system/auditd.service
  register: execstartpost_auditd_set
  when: ansible_os_family == "RedHat"
  changed_when: execstartpost_auditd_set.rc != 0
  failed_when: execstartpost_auditd_set.rc > 1

- name: set audit service execstartpost
  become: 'yes'
  lineinfile:
    regexp: '#ExecStartPost=-/sbin/auditctl -R /etc/audit/audit.rules'
    line: 'ExecStartPost=-/sbin/auditctl -R /etc/audit/audit.rules'
    dest: /usr/lib/systemd/system/auditd.service
    state: present
  when: ansible_os_family == "RedHat" and execstartpost_auditd_set.rc != 0
  tags:
    - auditd

- name: set audit action_mail_acct
  become: 'yes'
  lineinfile:
    regexp: "^action_mail_acct"
    line: "action_mail_acct = {{ auditd_action_mail_acct }}"
    dest: /etc/audit/auditd.conf
    mode: 0640
    state: present
    create: 'no'
  tags:
    - auditd

- name: set audit admin_space_left_action
  become: 'yes'
  lineinfile:
    regexp: "^admin_space_left_action"
    line: "admin_space_left_action = {{ auditd_admin_space_left_action }}"
    dest: /etc/audit/auditd.conf
    mode: 0640
    state: present
    create: 'no'
  tags:
    - auditd

- name: set audit max_log_file_action
  become: 'yes'
  lineinfile:
    regexp: "^max_log_file_action"
    line: "max_log_file_action = {{ auditd_max_log_file_action }}"
    dest: /etc/audit/auditd.conf
    mode: 0640
    state: present
    create: 'no'
  tags:
    - auditd

- name: set audit space_left_action
  become: 'yes'
  lineinfile:
    regexp: "^space_left_action"
    line: "space_left_action = {{ auditd_space_left_action }}"
    dest: /etc/audit/auditd.conf
    mode: 0640
    state: present
    create: 'no'
  tags:
    - auditd

- name: audit.rules
  become: 'yes'
  template:
    src: etc/audit/rules.d/hardening.rules.j2
    dest: /etc/audit/rules.d/hardening.rules
    backup: 'yes'
    mode: 0600
    owner: root
    group: root
  notify:
    - generate auditd
    - restart auditd
  tags:
    - auditd
    - audit.rules
...
