---
- name: restrict compiler access
  become: 'yes'
  file:
    owner: root
    group: root
    mode: 0750
    state: file
    follow: 'yes'
    path: "{{ item }}"
  ignore_errors: true
  with_items:
    - "{{ compilers }}"
  tags:
    - suid
...
