---
- name: add the nf_conntrack module
  become: 'yes'
  modprobe:
    name: nf_conntrack
    state: present
  tags:
    - conntrack
    - sysctl

- name: stat nf_conntrack_tcp_be_liberal
  become: 'yes'
  stat:
    path: /proc/sys/net/netfilter/nf_conntrack_tcp_be_liberal
  register: conntrackliberal
  tags:
    - conntrack
    - sysctl

- name: enable nf_conntrack_tcp_be_liberal to keep connections alive
  become: 'yes'
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: "1"
    state: present
    sysctl_set: 'yes'
    reload: 'yes'
  when: conntrackliberal.stat.exists and ansible_os_family == "Debian"
  tags:
    - conntrack
    - sysctl

- name: ufw installation
  become: 'yes'
  apt:
    name: "ufw"
    state: present
    install_recommends: 'no'
  when: ansible_os_family == "Debian"
  tags:
    - apt
    - packages
    - ufw

- name: firewalld installation
  become: 'yes'
  dnf:
    name: "firewalld"
    state: present
  when: ansible_os_family == "RedHat"
  tags:
    - dnf
    - packages
    - firewalld

- name: python-firewall installation
  become: 'yes'
  dnf:
    name: "python-firewall"
    state: present
  when: ansible_os_family == "RedHat" and ansible_python.version.major <= 2
  tags:
    - dnf
    - packages
    - firewalld

- name: python3-firewall installation
  become: 'yes'
  dnf:
    name: "python3-firewall"
    state: present
  when: ansible_os_family == "RedHat" and ansible_python.version.major >= 3
  tags:
    - dnf
    - packages
    - firewalld

- name: set ufw IPT_SYSCTL
  become: 'yes'
  lineinfile:
    regexp: "^IPT_SYSCTL="
    line: "IPT_SYSCTL=/etc/sysctl.conf"
    dest: /etc/default/ufw
    mode: 0640
    state: present
    create: 'no'
    backrefs: 'yes'
  tags:
    - ufw
  when: ansible_os_family == "Debian"

- name: register ufw rules
  become: 'yes'
  shell: |
    set -o pipefail
    ufw show added | grep '^ufw' | grep -v "'ansible\smanaged'" | sed 's/ufw //g'
  args:
    executable: /bin/bash
  failed_when: ufw_not_managed.rc > 1
  changed_when: false
  register: ufw_not_managed

- name: delete unmanaged ufw rules
  become: 'yes'
  command: ufw delete {{ item }}
  when: ufw_not_managed.stdout_lines | length > 0
  with_items:
    - "{{ ufw_not_managed.stdout_lines }}"

- name: allow loopback traffic in
  become: 'yes'
  ufw:
    rule: allow
    interface: lo
    direction: in
    comment: ansible managed
  when: ansible_os_family == "Debian"
  tags:
    - ufw

- name: allow loopback traffic out
  become: 'yes'
  ufw:
    rule: allow
    interface: lo
    direction: out
    comment: ansible managed
  when: ansible_os_family == "Debian"
  tags:
    - ufw

- name: allow ssh ufw
  become: 'yes'
  ufw:
    rule: limit
    src: "{{ item }}"
    port: "{{ sshd_port|int }}"
    proto: tcp
    comment: ansible managed
  with_items:
    - "{{ sshd_admin_net }}"
  when: ansible_os_family == "Debian"
  tags:
    - ufw
    - ssh

- name: allow outgoing specified ufw ports
  become: 'yes'
  ufw:
    rule: allow
    port: '{{ item|int }}'
    direction: out
    comment: ansible managed
  with_items:
    - "{{ ufw_outgoing_traffic }}"
  when: ansible_os_family == "Debian"
  tags:
    - ufw

# https://github.com/ansible/ansible/issues/45446
- name: enable ufw and set default deny incoming
  become: 'yes'
  ufw:
    state: enabled
    direction: incoming
    policy: deny
    log: 'yes'
    logging: low
    comment: ansible managed
  when: ansible_os_family == "Debian"
  tags:
    - ufw

- name: enable ufw and set default deny outgoing
  become: 'yes'
  ufw:
    state: enabled
    direction: outgoing
    policy: deny
    log: 'yes'
    logging: low
    comment: ansible managed
  when: ansible_os_family == "Debian"
  tags:
    - ufw

- name: deny loopback network traffic
  become: 'yes'
  ufw:
    rule: deny
    src: '{{ item }}'
    comment: ansible managed
  loop:
    - 127.0.0.0/8
    - ::1
  when: ansible_os_family == "Debian"
  tags:
    - ufw

- name: stat firewalld conf
  become: 'yes'
  stat:
    path: /etc/firewalld/firewalld.conf
  register: firewalldconf
  tags:
    - firewalld

- name: set firewalld DefaultZone
  become: 'yes'
  lineinfile:
    regexp: "^DefaultZone="
    line: "DefaultZone=public"
    dest: /etc/firewalld/firewalld.conf
    mode: 0640
    state: present
    create: 'no'
    backrefs: 'yes'
  when: firewalldconf.stat.exists
  tags:
    - firewalld

- name: enable firewalld
  become: 'yes'
  service:
    name: firewalld
    state: started
    enabled: 'yes'
  when: firewalldconf.stat.exists
  tags:
    - firewalld

- name: allow firewalld ssh
  become: 'yes'
  firewalld:
    port: "{{ sshd_port }}/tcp"
    zone: public
    immediate: 'yes'
    permanent: 'true'
    state: enabled
  when: ansible_os_family == "RedHat"
  tags:
    - firewalld
...
