version: "3.7"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail.${ROOT_DOMAIN}
    domainname: ${ROOT_DOMAIN}
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./maildata:/var/mail
      - ./mailstate:/var/mail-state
      - ./maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ./etc/dovecot/conf.d/10-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: unless-stopped

  # Full text search
  dovecot-solr:
    image: lmmdock/dovecot-solr:latest
    container_name: dovecot-solr
    volumes:
      - ./solr-dovecot:/opt/solr/server/solr/dovecot
    restart: unless-stopped