- name: Setup Git
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Include encrypted Samba credentials
      include_vars: ../../../vaults/samba_users.vault
      
    - name: Set the hostname
      include_role:
        name: set_hostname
      vars:
        hostname: git
        localdomain: land

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Git
            port: 80
          - service: SSH
            port: 22

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower