- import_playbook: ../../raspios-template.yml

# https://smallstep.com/blog/build-a-tiny-ca-with-raspberry-pi-yubikey/
- name: Provision Certificate Authority on Raspberry Pi
  hosts: default
  remote_user: ubuntu
  collections:
    - professorsalty.homelab
    - community.general
    - ansible.posix

  tasks:
    - name: Set the CA hostname
      include_role:
        name: set_hostname
      vars:
        hostname: tinyca
        localdomain: land

    - name: Install noise generator driver and tools
      become: yes
      with_itms:
        - infnoise_0.3.1_armhf.deb
        - infnoise-tools_0.3.1_armhf.deb
      apt:
        deb: "https://github.com/13-37-org/infnoise/releases/download/0.3.1/{{ item }}"
        state: present

    - name: Reboot the machine
      become: yes
      reboot:

    - name: Install dependencies
      become: yes
      with_items:
        - libpcsclite-dev
        - gcc
        - make
        - pkg-config
        - yubikey-manager
      package:
        name: "{{ item }}"
        state: present

    - name: Create /etc/step-ca
      become: yes
      file:
        path: /etc/step-ca
        state: directory

    - name: Install golang
      include_role:
        name: install_golang

    - name: Download step-ca source
      get_url:
        url: https://github.com/smallstep/certificates/archive/v0.15.5.tar.gz
        dest: /home/ubuntu
        mode: 777
        owner: ubuntu
        group: ubuntu

    - name: Unzip the archive
      unarchive:
        remote_src: yes
        src: /home/ubuntu/v0.15.5.tar.gz 
        dest: /home/ubuntu

    - name: Bootstrap make
      make:
        chdir: /home/ubuntu/certificates-0.15.5/
        target: bootstrap

    - name: Build step-ca from source
      make:
        chdir: /home/ubuntu/certificates-0.15.5/
        params:
          # empty GOFLAGS on build enable experimental YubiKey support in step-ca
          GOFLAGS: ""

    - name: Copy the step-ca binary
      become: yes
      copy:
        remote_src: yes
        src: /home/ubuntu/certificates-0.15.5/bin/step-ca
        dest: /usr/local/bin/

    - name: Add capability to setp-ca binary
      capabilities:
        path: /usr/local/bin/step-ca
        capability: cap_net_bind_service
        state: present

    - name: Download step binary
      get_url:
        url: https://github.com/smallstep/cli/releases/download/v0.15.3/step_linux_0.15.3_arm64.tar.gz
        dest: /home/ubuntu
        mode: 777
        owner: ubuntu
        group: ubuntu

    - name: Unzip the step binary
      unarchive:
        remote_src: yes
        src: /home/ubuntu/step_linux_0.15.3_arm64.tar.gz
        dest: /home/ubuntu

    - name: Copy the step binary
      copy:
        remote_src: yes
        src: /home/ubuntu/step_0.15.3/bin/step
        dest: /usr/local/bin/

    - name: Amend /etc/crypttab to automount usb drive
      become: yes
      lineinfile:
        path: /etc/crypttab
        state: present
        line: keys /dev/sda1 /etc/keyspassword

    - name: Mount the usb drive
      become: yes
      ansible.posix.mount:
        state: mounted
        path: /mnt/keys
        src: /dev/mapper/keys
        fstype: auto
        opts: nosuid,nodev,nofail

    - name: Set udev rules
      become: yes
      copy:
        dest: /etc/udev/rules.d/75-yubikey.rules
        content: |
          ACTION=="add", SUBSYSTEM=="usb", ENV{PRODUCT}=="1050/407/*", TAG+="systemd", SYMLINK+="yubikey"
          ACTION=="remove", SUBSYSTEM=="usb", ENV{PRODUCT}=="1050/407/*", TAG+="systemd"

    - name: Create systemd entry
      copy:
        dest: /etc/systemd/system/step-ca.service
        content: |
          [Unit]
          Description=step-ca
          BindsTo=dev-yubikey.device
          After=dev-yubikey.device

          [Service]
          User=step
          Group=step
          ExecStart=/bin/sh -c '/usr/local/bin/step-ca /etc/step-ca/config/ca.json'
          Type=simple
          Restart=on-failure
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Setup the CA
      become: yes
      shell:
        cmd: step ca init --name "Tiny CA" \
                --password-file <(echo "foo") \
                --provisioner-password-file <(echo "foo") \
                --root ./root_ca.crt
                --ssh \ 
                --with-ca-url "localhost" \
                --address ":443" \
                --dns "localhost" \
                --provisioner "admin@intothe.stream" \
                --key <(step crypto key format \
                                --no-password --insecure --pem \
                                --password-file <(echo "bar") ./root_ca_key) \

    - name: Add ACME provisioner to step-ca config
      become: yes
      shell:
        cmd: step ca provisioner add acme --type acme --ca-config /etc/step-ca/config/ca.json

    - name: Install Netbox
      include_role:
        - name: install_netbox

    - name: reboot to finish
      become: yes
      reboot: