version: "3.7"
services:
  calibre-web:
    image: technosoft2000/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - USE_CONFIG_DIR=true
    expose:
      - 8083
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BOOKS_ROOT}:/books
      - ${SERVICES_ROOT}/${CALIBRE_WEB_ROOT:-calibre-web}:/calibre-web