version: "3.7"
services:
  ###############################
  #     docker-socket-proxy     #
  ###############################
  dockerproxy:
    image: tecnativa/docker-socket-proxy
    container_name: dockerproxy
    restart: unless-stopped
    environment:
      - POST=1
      - BUILD=1
      - CONTAINERS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - SESSION=1
      - SWARM=1
      - SYSTEM=1
      - VOLUMES=1
      - TZ
    expose:
      - 2375
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  ###############################
  #          watchtower         #
  ###############################
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    command: -H tcp://dockerproxy:2375 --interval 30

  ###############################
  #         Sonarr              #
  ###############################
  sonarr:
    image: ghcr.io/linuxserver/sonarr:preview
    container_name: sonarr
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "8989:8989"
    volumes:
      - ${SERVICES_ROOT}/${SONARR_ROOT:-sonarr}/config:/config
      - ${SHOWS_ROOT}:/tv
      - ${FINISHED_DOWNLOADS}:/downloads
    restart: unless-stopped

  ###############################
  #         Radarr              #
  ###############################
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "7878:7878"
    volumes:
      - ${SERVICES_ROOT}/${RADARR_ROOT:-radarr}/config:/config
      - ${MOVIES_ROOT}:/movies
      - ${FINISHED_DOWNLOADS}:/downloads
    restart: unless-stopped

  ###############################
  #         Lidarr              #
  ###############################
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "8686:8686"
    volumes:
      - ${SERVICES_ROOT}/${LIDARR_ROOT:-lidarr}/config:/config
      - ${MUSIC_ROOT}:/music
      - ${FINISHED_DOWNLOADS}:/downloads
    restart: unless-stopped

  ###############################
  #         Bazarr              #
  ###############################
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "6767:6767"
    volumes:
      - ${SERVICES_ROOT}/${BAZARR_ROOT:-bazzar}/config:/config
      - ${MOVIES_ROOT}:/movies
      - ${SHOWS_ROOT}:/tv
    restart: unless-stopped

  ###############################
  #         Mylarr              #
  ###############################
  mylar:
    image: ghcr.io/linuxserver/mylar3
    container_name: mylar
    environment:
      - PUID
      - PGID
    volumes:
      - ${SERVICES_ROOT}/${MYLAR_ROOT:-mylar}:/config
      - ${COMICS_ROOT}:/comics
      - ${FINISHED_DOWNLOADS}:/downloads
    ports:
      - "8090:8090"
    restart: unless-stopped

  ###############################
  #         Jackett             #
  ###############################
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "9117:9117"
    volumes:
      - ${SERVICES_ROOT}/${JACKETT_ROOT:-jackett}/config:/config
      - ${FINISHED_DOWNLOADS}:/downloads
    restart: unless-stopped

  ###############################
  #         nzbhydra            #
  ###############################
  nzbhydra:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra
    environment:
      - PUID
      - PGID
    ports:
      - "5076:5076"
    volumes:
      - ${SERVICES_ROOT}/${NZBHYDRA_ROOT:-nzbhydra}/config:/config
      - ${FINISHED_DOWNLOADS}:/downloads
    restart: unless-stopped

  ###############################
  #           Ombi              #
  ###############################
  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "3579:3579"
    volumes:
      - ${SERVICES_ROOT}/${OMBI_ROOT:-ombi}:/config
    restart: unless-stopped

  ##############################
  #        LazyLibrian         #
  ##############################
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    ports:
      - 5299:5299
    environment:
      - PUID
      - PGID
      - TZ
      - DOCKER_MODS=linuxserver/calibre-web:calibre #optional
    volumes:
      - ${SERVICES_ROOT}/${LAZYLIBRARIAN_ROOT:-lazylibrarian}/config:/config
      - ${FINISHED_DOWNLOADS}:/downloads
      - ${BOOKS_ROOT}:/books
    restart: unless-stopped

  ##############################
  #        Readarr             #
  ##############################
  readarr:
    image: hotio/readarr:nightly
    container_name: readarr  
    restart: unless-stopped  
    ports:  
      - 8787:8787  
    volumes:  
      - ${SERVICES_ROOT}/${READARR_ROOT:-readarr}:/config  
      - ${BOOKS_ROOT}:/books  
      - ${BOOKS_ROOT}:/audiobooks  
    environment:  
      - PUID
      - PGID
      - TZ

  ##############################
  #           NZBGet           #
  ##############################
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${SERVICES_ROOT}/${NABGET_ROOT:-nzbget}:/config
      - ${INTERMEDIATE_DOWNLOADS}:/intermediate
      - ${FINISHED_DOWNLOADS}:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
