- name: Setup downloader
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../default_env_vars.yml

    - name: Include encrypted Samba credentials
      include_vars: ../../../vaults/samba_users.vault

    - name: Create filesystems
      with_items:
        - "/dev/sdb"
        - "/dev/sdc"
      community.general.parted:
        device: "{{ item }}"
        number: 1
        state: present
        fs_type: ext4

    - name: Mount the big drive
      ansible.posix.mount:
        src: "/dev/sdb1"
        path: "/mnt/bigdrive"
      
    - name: Mount the fast drive
      ansible.posix.mount:
        src: "/dev/sdc1"
        path: "/mnt/intermediate"

    - include_role: 
        name: smbmount

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .