version: "3.7"
networks:
  proxy:
  authelia:

services:
  ###############################
  #           Authelia          #
  ###############################
  authelia:
    image: authelia/authelia
    container_name: authelia
    depends_on:
      - authelia-cache
      - authelia-db
    volumes:
      - ${SERVICES_ROOT}/${AUTHELIA_ROOT:-authelia}/core:/var/lib/authelia
      - ./configs/authelia/configuration.yml:/etc/authelia/configuration.yml:ro
      - ./configs/authelia/secrets:/etc/secrets/authelia:ro
      - ./configs/openldap/secrets:/etc/secrets/openldap:ro
    ports:
      - "9091:9091"
    networks:
      - authelia
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`logins.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.authelia.entrypoints=secure"
      - "traefik.http.routers.authelia.tls=true"
    restart: unless-stopped
    environment:
      - AUTHELIA_SESSION_SECRET_FILE=/etc/secrets/authelia/session
      - AUTHELIA_JWT_SECRET_FILE=/etc/secrets/authelia/jwt_secret
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/etc/secrets/openldap/admin_password
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/etc/secrets/authelia/postgres_password
      - TZ

  authelia-cache:
    image: redis:alpine
    container_name: authelia-cache
    environment:
      - TZ
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - authelia

  authelia-db:
    image: postgres:12-alpine
    container_name: authelia-db
    restart: unless-stopped
    expose:
      - 5432
    networks:
      - authelia
    environment:
      - POSTGRES_DB=authelia
      - POSTGRES_USER=authelia
      - POSTGRES_PASSWORD_FILE=/etc/secrets/postgres_password
      - TZ
    volumes:
      - ${SERVICES_ROOT}/${AUTHELIA_ROOT:-authelia}/db:/var/lib/postgresql/data
      - ./configs/authelia/secrets:/etc/secrets:ro

  ###############################
  #           Traefik           #
  ###############################
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ
    env_file:
      - .env
      - providers.env
    command:
      - --certificatesresolvers.le.acme.email=${NOTIFICATIONS_EMAIL:?Please supply LetsEncrypt with an email}
    labels:
      - "traefik.enable=true"
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
    volumes:
      - ./configs/traefik/static.yml:/traefik.yml
      - ./configs/traefik/dynamic.yml:/dynamic.yml
      - ${SERVICES_ROOT}/${TRAEFIK_ROOT:-traefik}/le:/le

  ###############################
  #           Gitea             #
  ###############################
  gitea:
    image: gitea/gitea:1.13.2
    container_name: gitea
    environment:
      - USER_UID=${PUID}
      - USER_GID=${PGID}
    restart: unless-stopped
    volumes:
      - ${MIRRORED_REPO_DRIVE}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
