version: "3.7"
services:
  ###############################
  #           rtorrent          #
  ###############################
  rutorrent:
    image: romancin/rutorrent-flood:latest
    container_name: rutorrent-flood
    tty: true
    volumes:
      - ${SERVICES_ROOT}/${RTOORENT_ROOT:-rtorrent}:/config
      - ${TORRENTS_ROOT}:/downloads
    environment:
      - PUID
      - PGID
      - TZ
      - CREATE_SUBDIR_BY_TRACKERS=NO
      - SSL_ENABLED=NO
      - RT_TOKEN=
      - RT_MASTERS=
    ports:
      - "80:80"
      - "52316:52316"
      - "3000:3000"