- name: Setup torrent
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Include encrypted Samba credentials
      include_vars: ../../../vaults/samba_users.vault

    - name: Mount samba shares
      include_role:
        name: mount_smb_shares
      vars:
        project_name: torrent
        smb_credentials:
          - username: torrentsuser
            password:
            sharepath: torrents

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: RUTorrent Flood
            port: 80
          - service: RUTorrent Flood
            port: 52316
          - service: RUTorrent Flood
            port: 3000

    - name: Run docker-compose file
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: "."
        state: present

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower