version: "3.7"
services:
  calibre-web:
    image: technosoft2000/calibre-web
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PGID=1000
      - PUID=1000
      - USE_CONFIG_DIR=true
    expose:
      - 8083
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BOOKS_ROOT}:/books
      - ${SERVICES_ROOT}/${CALIBRE_WEB_ROOT:-calibre-web}/config:/calibre-web/config
      - ${SERVICES_ROOT}/${CALIBRE_WEB_ROOT:-calibre-web}/kindlegen:/calibre-web/kindlegen
      - ${SERVICES_ROOT}/${CALIBRE_WEB_ROOT:-calibre-web}/app:/calibre-web/app
      - ${SERVICES_ROOT}/${CALIBRE_WEB_ROOT:-calibre-web}/db:/calibre-web/db