- name: Setup Bitwarden
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Set the hostname
      include_role:
        name: set_hostname
      vars:
        hostname: bitwarden
        localdomain: land

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Bitwarden
            port: 80

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower