- name: Setup mediaserver
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Set hostname
      include_role:
        name: set_hostname
      vars:
        hostname: mediaserver

    - name: Mount the drives
      include_role:
        name: create_filesystem
      vars: 
        drives:
          - device: sdb
            mount_point: transcode
            
    - name: Mount samba shares
      include_role:
        name: mount_smb_shares
      vars:
        project_name: mediaserver
        smb_credentials:
          - username: mediauser
            password:
            sharepath: media

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: Jellyfin
            port: "{{jellyfin_port}}"
          - service: Airsonic
            port: "{{airsonic_port}}"
          - service: CalibreWeb
            port: "{{calibre_port}}"

    - name: Jellyfin
      community.general.docker_container:
        image: jellyfin/jellyfin
        name: jellyfin
        restart_policy: unless-stopped
        published_ports:
          - "{{jellyfin_port}}:8096"
        volumes:
          - "{{MEDIA_ROOT}}:/media:ro"
          - "{{SERVICES_ROOT}}/jellyfin/config:/config"
        env:
          - PUID
          - PGID
          - TZ

    - name: Airsonic
      community.general.docker_container:
        image: airsonicadvanced/airsonic-advanced:latest
        container_name: airsonic
        restart_policy: unless-stopped
        env:
          - PUID
          - PGID
          - TZ
        published_ports:
          - "{{airsonic_port}}:8080"
        volumes:
          - "{{SERVICES_ROOT}}/airsonic/var/airsonic"
          - "{{MEDIA_ROOT}}/music:/var/music"
          - "{{MEDIA_ROOT}}/podcasts:/var/podcasts"
          - "{{MEDIA_ROOT}}/playlists:/var/playlists"
          - ./sites-enabled:/etc/apache2/sites-enabled

    - name: Calibre Web
      community.general.docker_container:
        image: technosoft2000/calibre-web
        name: calibre-web
        restart_policy: unless-stopped
        env:
          - PUID
          - PGID
          - USE_CONFIG_DIR=true
          - TZ
        pubished_ports:
          - "{{calibre_port}}:8083"
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - "{{BOOKS_ROOT}}:/books"
          - "{{SERVICES_ROOT}}/calibre-web:/calibre-web"

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower