---
- name: Setup Centos 8
  hosts: default
  remote_user: root
  vars_files: ../vars/freeipa-vars.yml
  collections:
    - freeipa.ansible_freeipa
    - professorsalty.homelab

  pre_tasks:
    - include_role:
        name: add_key

  tasks:
    - include_role:
        name: add_epel_powertools
    - include_role: 
        name: install_netdata
    - include_role: 
        name: install_server_packages
    - include_role: 
        name: direct_rsyslog_to_server
    - include_role: 
        name: ipaserver