- name: Provision RaspiOS template
  hosts: default
  remote_user: pi
  collections:
      - professorsalty.homelab

  pre_tasks:
    - include_role: 
        name: addkey

  tasks:
    - include_role: 
        name: setup
    - include_role: 
        name: rsyslog
    - include_role: 
        name: netdata
    - include_role:
        name: rnngtools
    - include_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_automatic_reboot: yes
        unattended_origins_patterns:
          - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'