- name: Provision RaspiOS template
  hosts: default
  collections:
      - professorsalty.homelab

  pre_tasks:
    - include_role: 
        name: add_key

  tasks:
    - include_role: 
        name: install_server_packages
    - include_role: 
        name: direct_rsyslog_to_server
    - include_role: 
        name: install_netdata
    - include_role:
        name: install_rng_tools
    - include_role:
        name: setup_raspi_display
    - include_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_automatic_reboot: yes
        unattended_origins_patterns:
          - 'origin=Raspbian,codename=${distro_codename},label=Raspbian'