- import_playbook: ../../raspios-template.yml

- name: Provision PiHole on Raspberry Pi
  hosts: default
  remote_user: root
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Install Docker
      include_role: 
        name: install_docker

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower

    - name: Execute docker-compose
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: .