version: "3.7"
services:
  portus:
    image: opensuse/portus:2.4
    container_name: portus
    restart: unless-stopped
    environment:
      - PORTUS_CHECK_SSL_USAGE_ENABLED=false
      - PORTUS_SECRET_KEY_BASE
      - PORTUS_PASSWORD
      - PORTUS_KEY_PATH=/certificates/portus.key
      - CCONFIG_PREFIX=PORTUS
      - RAILS_SERVE_STATIC_FILES=true
      - PORTUS_EMAIL_FROM=notifications@${ROOT_DOMAIN}
      - PORTUS_EMAIL_NAME=Portus
      - PORTUS_EMAIL_REPLY_TO=notifications@${ROOT_DOMAIN}
      - PORTUS_EMAIL_SMTP_ENABLED=true
      - PORTUS_EMAIL_SMTP_ADDRESS=smtp
      - PORTUS_EMAIL_SMTP_DOMAIN=${ROOT_DOMAIN}
      - PORTUS_EMAIL_SMTP_PORT=587
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=openldap
      - PORTUS_LDAP_PORT=389
      - PORTUS_LDAP_UID=uid
      - PORTUS_LDAP_BASE=ou=people,${LDAP_LOGIN_BASE}
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=cn=admin,${LDAP_LOGIN_BASE}
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - PORTUS_LDAP_GROUP_BASE=cn=dev,ou=groups,${LDAP_LOGIN_BASE}
      - PORTUS_LDAP_GUESS_EMAIL_ENALBED=true
      - PORTUS_LDAP_GUESS_EMAIL_ATTR=mail
      - PORTUS_DB_HOST=portus-db
      - PORTUS_DB_DATABASE=portus
      - PORTUS_DB_USERNAME=portus
      - PORTUS_DB_PASSWORD
      - PORTUS_MACHINE_FQDN_VALUE=registry.${ROOT_DOMAIN}
      - TZ

  portus-db:
    image: linuxserver/mariadb
    container_name: portus-db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=${PORTUS_DB_ADMIN_PASSWORD:?Admin password for portus-db must be set!}
      - MYSQL_DATABASE=portus
      - MYSQL_USER=portus
      - MYSQL_PASSWORD=${PORTUS_DB_PASSWORD:?User password for portus must be set!}
      - TZ
    volumes:
      - ${SERVICES_ROOT}/${PORTUS_ROOT:-portus}/db:/config
    restart: unless-stopped
