- name: Setup MotionEye server
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Set hostname
      include_role:
        name: set_hostname
      vars:
        hostname: motioneye

    - name: Mount the network shares
      include_role:
        name: mount_smb_shares
      vars:
        project_name: motioneye
            
        smb_credentials:
          - username: mediauser
            password:
            sharepath: media

    - name: Allow ports 
      include_role:
        name: ufw-allow-ports
      vars:
        configs:
          - service: MotionEye
            port: 8081
          - service: MotionEye
            port: 8765

    - name: MotionEye
      community.general.docker_container:
        name: motioneye
        image: ccrisan/motioneye:master-amd64
        published_ports:
          - "8081:8081"
          - "8765:8765"
        env:
          - TZ
        volumes:
          - ${SERVICES_ROOT}/${MOTIONEYE_ROOT:-motioneye}/etc:/etc/motioneye
          - ${SERVICES_ROOT}/${MOTIONEYE_ROOT:-motioneye}/var/lib:/var/lib/motioneye
        restart: unless-stopped

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower