- name: Provision Ubuntu Template 
  hosts: default
  collections:
      - professorsalty.homelab

  pre_tasks:
    - include_role: 
        name: add_key

  tasks:
    - include_role: 
        name: install_server_packages
    - include_role: 
        name: direct_rsyslog_to_server
    - include_role: 
        name: install_netdata
    - include_role:
        name: jnv.unattended-upgrades
        apply:
          become: true
      vars:
        unattended_automatic_reboot: yes
        unattended_origins_patterns:
          - 'origin=Ubuntu,archive=${distro_codename}-security'
          - 'o=Ubuntu,a=${distro_codename}'
          - 'o=Ubuntu,a=${distro_codename}-updates'
          - 'o=Ubuntu,a=${distro_codename}-proposed-updates'
    - include_role:
        name: konstruktoid.hardening
      vars:
        system_upgrade: yes
        packages_blocklist:
          - telnet*
          - tftp*
        sshd_print_motd: no
        sshd_use_dns: yes
    - include_role:
        name: prepare_cloudinit
    - include_role:
        name: remove_netplan