- name: Provision Ubuntu Template for Docker
  hosts: default
  become: true
  remote_user: toor

  pre_tasks:
    - name: Set authorized key for user, copying it from current user
      ansible.posix.authorized_key:
        user: toor
        state: present
        key: "{{ lookup('file', public_key_file) }}"

  tasks:
    - name: Install docker packages
      ansible.builtin.apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
          ]
        state: present
        update_cache: yes
      tags:
        - docker
    # - name: Disable swap
    - name: Add Dockers official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags:
        - docker
    - name: Verify that we have the key with the fingerprint
      ansible.builtin.apt_key:
        id: 0EBFCD88
        state: present
      tags:
        - docker
    - name: Set up the stable repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes
      tags:
        - docker
    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: yes
      tags:
        - docker
    - name: Install docker
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes
      notify: start_docker
      tags:
        - docker
    - name: Install docker-compose
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'
    - name: Add remote "toor" user to "docker" group
      ignore_errors: "{{ ansible_check_mode }}"
      ansible.builtin.user:
        name: toor
        group: docker
        append: yes
      tags:
        - docker
    - name: Install docker-compose
      ansible.builtin.get_url:
        url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"
    - name: Install mosh (MObile SHell)
      ansible.builtin.apt:
        name: mosh
        state: present
    - name: Install fish
      ansible.builtin.apt:
        name: fish
        state: present
        update_cache: yes
    - name: Change shell to fish
      ansible.builtin.user:
        name: toor
        shell: /usr/bin/fish
    - name: Setup rsyslog
      ansible.builtin.lineinfile:
        line: $PreserveFQDN on\n\n*.* @{{ syslog_server_address }}:514
        path: /etc/rsyslog.conf
    - name: Install Netdata dependencies
      ansible.builtin.apt:
        name:
          [
            "zlib1g-dev",
            "uuid-dev",
            "libuv1-dev",
            "liblz4-dev",
            "libjudy-dev",
            "libssl-dev",
            "libmnl-dev",
            "gcc",
            "make",
            "git",
            "autoconf",
            "autoconf-archive",
            "autogen",
            "automake",
            "pkg-config",
            "curl",
            "python",
            "cmake",
          ]
        state: present
        update_cache: yes
    - name: Clone Netdata repo
      ansible.builtin.git:
        depth: 1
        dest: /opt/netdata
        repo: https://github.com/netdata/netdata.git
    - name: Get Netdata status
      ansible.builtin.stat:
        path: /opt/netdata
      register: netdata_clone
    - name: Install Netdata using the script in the repo
      when: netdata_clone.stat.isdir| default(False) and netdata_clone.stat.isdir
      ansible.builtin.shell: bash netdata-installer.sh --dont-wait --libs-are-really-here
      args:
        chdir: /opt/netdata
      notify: start_netdata

  handlers:
    - name: start_netdata
      ansible.builtin.service:
        name: netdata
        state: started

    - name: start_docker
      ansible.builtin.service:
        name: docker
        state: started
