version: "3.7"
services:
  nextcloud-server:
    image: nginx:alpine
    restart: unless-stopped
    container_name: nextcloud-server
    depends_on:
      - nextcloud-data
    volumes:
      - nextcloud:/var/www/html:ro
      - ./configs/nextcloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${NEXTCLOUD_DATA}:/var/www/html/data
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/config:/var/www/html/config
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/custom_apps:/var/www/html/custom_apps
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/themes:/var/www/html/themes
    environment:
      - TZ

  nextcloud-data:
    image: nextcloud:18-fpm-alpine
    restart: unless-stopped
    container_name: nextcloud
    depends_on:
      - nextcloud-db
      - nextcloud-cache
    volumes:
      - nextcloud:/var/www/html
      - ${NEXTCLOUD_DATA}:/var/www/html/data
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/config:/var/www/html/config
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/custom_apps:/var/www/html/custom_apps
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/themes:/var/www/html/themes
    environment:
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - POSTGRES_HOST=nextcloud-db
      - POSTGRES_DB=nextcloud
      - NEXTCLOUD_HOSTNAME=cloud.${ROOT_DOMAIN}
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${ROOT_DOMAIN} ${ROOT_DOMAIN} localhost
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=nextcloud-cache
      - SMTP_HOST=smtp
      - SMTP_AUTH_TYPE=NONE
      - SMTP_PORT=587
      - MAIL_FROM_ADDRESS=notifications@${ROOT_DOMAIN}
      - TZ

  nextcloud-db:
    image: postgres:12-alpine
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - TZ
    volumes:
      - ${SERVICES_ROOT}/${NEXTCLOUD_ROOT:-nextcloud}/db:/var/lib/postgresql/data

  nextcloud-cache:
    image: redis:alpine
    container_name: nextcloud-cache
    restart: unless-stopped
    environment:
      - TZ
