- name: Setup Bitwarden host
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Set hostname
      include_role:
        name: set_hostname
      vars:
        hostname: bitwarden

    - name: Download Bitwarden script
      get_url:
        dest: bitwarden.sh
        url: https://go.btwrdn.co/bw-sh
        mode: +x

    - name: Run the script
      shell:
        cmd: ./bitwarden.sh install

    - name: Copy the config override
      copy:
        src: global.override.env
        dest: ./bwdata/env/global.override.env

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower