version: "3.7"
services:
  ###############################
  #           Filestash         #
  ###############################
  filestash:
    container_name: filestash
    image: machines/filestash
    restart: unless-stopped
    environment:
      - TZ
      - APPLICATION_URL=files.${SEARCH_DOMAIN}
      - ONLYOFFICE_URL=http://onlyoffice
    ports:
      - "8334:8334"

  onlyoffice:
    container_name: filestash_oods
    image: onlyoffice/documentserver
    restart: unless-stopped
    environment:
      - TZ
    