- name: Setup filebrowser
  hosts: default
  remote_user: toor
  collections:
      - professorsalty.homelab

  tasks:
    - name: Include common env vars
      include_vars: ../../default_env_vars.yml

    - name: Set hostname
      include_role:
        name: set_hostname
      vars:
        hostname: filebrowser

    - name: Mount samba shares
      include_role:
        name: mount_smb_shares
      vars:
        smb_credentials:
          - username: storageuser
            password:
            sharepath: storage

    - name: Allow ports 
      include_role:
        name: ufw_allow_ports
      vars:
        configs:
          - service: filestash
            port: 8334

    - name: Run docker-compose file
      environment: "{{ env_vars }}"
      community.general.docker_compose:
        project_src: "."
        state: present

    - name: Run watchtower with proxy
      include_role:
        name: run_watchtower